version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile

    volumes:
      - ./backend/src:/project/backend:cached

    network_mode: service:db

    command: sleep infinity

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile

    volumes:
      - ./frontend/src:/project/frontend:cached
      - /project/frontend/node_modules/
    ports:
      #   - 3000:3000
      - 5173:5173 # for VITE
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8000:8000

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  postgres-data: null
